import { Orbitron } from 'next/font/google';
import Footer from './components/Footer/Footer';
import './globals.css';
import NavBar from './Header/NavBar';

// Configuration de la police Playfair Display
const orbitron = Orbitron({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={orbitron.className}>
        <header>
          <NavBar name_li1="Acceuil" name_li2="Produits" name_li3="A Propos" />
        </header>
        <main>{children}</main>
        <footer>
          <Footer element1="lien1" element2="lien2" element3="lien3" />
        </footer>
      </body>
    </html>
  );
}
